package(
    default_visibility = ["//:wizard_package_group"],
)

licenses(["notice"])

filegroup(
    name = "wizard_profile",
    srcs = ["wizard.provisionprofile"],
)

filegroup(
    name = "agent_profile",
    srcs = ["Agent.provisionprofile"],
)

filegroup(
    name = "notifications_profile",
    srcs = ["Notifications.provisionprofile"],
)
